#! /bin/bash
rm -f ~/.vimrc ~/.tmux.config

[[ -d ~/.local/bin ]] || mkdir -p ~/.local/bin

# vim config
[[ -d ~/.vim ]] || ln -sf ~/configure/vim ~/.vim
[[ -x ~/configure/vim/bundle ]] || (mkdir -p ~/configure/vim/bundle && git clone https://github.com/gmarik/Vundle.vim.git ~/configure/vim/bundle/Vundle.vim)
ln -sf ~/configure/vimrc ~/.vimrc

# nvim config
[[ -d ~/.config/nvim ]] || cp -r ~/configure/nvim ~/.config/nvim

# tmux config
ln -sf ~/configure/tmux.conf ~/.tmux.conf

# zsh plugin config
[[ -d ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting ]] || git clone --depth=1 https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
[[ -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]] || git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
[[ -d ~/.oh-my-zsh/custom/plugins/history-search-multi-word ]] || git clone --depth=1 https://github.com/zdharma-continuum/history-search-multi-word ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/history-search-multi-word
[[ -d ~/.oh-my-zsh/powerlevel10k ]] || (git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/powerlevel10k && echo 'source ~/.oh-my-zsh/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc)
[[ -d ~/.oh-my-zsh/custom/plugins/zsh_codex ]] || git clone https://github.com/tom-doerr/zsh_codex.git ~/.oh-my-zsh/custom/plugins/zsh_codex

# wezterm config
[[ -f ~/.wezterm.lua ]] || ln -s ~/configure/wezterm.lua ~/.wezterm.lua

# git config
[[ -f ~/.gitconfig ]] || ln -s ~/configure/gitconfig ~/.gitconfig
