#! /bin/bash
rm -f ~/.vimrc ~/.tmux.config

# path config
[[ -d ~/.local/bin ]] || mkdir -p ~/.local/bin

# editor config
# vim config
[[ -d ~/.SpaceVim ]] || curl -sLf https://spacevim.org/install.sh | bash

# nvim config
[[ -d ~/.config/nvim ]] || cp -r ~/configure/nvim ~/.config/nvim

# tmux config
ln -sf ~/configure/tmux.conf ~/.tmux.conf

# zsh plugin config
[[ -d ~/.oh-my-zsh/custom/plugins/fast-syntax-highlighting ]] || git clone --depth=1 https://github.com/zdharma-continuum/fast-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fast-syntax-highlighting
[[ -d ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]] || git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
[[ -d ~/.oh-my-zsh/custom/plugins/history-search-multi-word ]] || git clone --depth=1 https://github.com/zdharma-continuum/history-search-multi-word ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/history-search-multi-word
[[ -d ~/.oh-my-zsh/powerlevel10k ]] || (git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/powerlevel10k && echo 'source ~/.oh-my-zsh/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc)
[[ -d ~/.oh-my-zsh/custom/plugins/zsh_codex ]] || git clone https://github.com/tom-doerr/zsh_codex.git ~/.oh-my-zsh/custom/plugins/zsh_codex

# wezterm config
[[ -f ~/.wezterm.lua ]] || ln -s ~/configure/wezterm.lua ~/.wezterm.lua

# git config
[[ -f ~/.gitconfig ]] || ln -s ~/configure/gitconfig ~/.gitconfig

# zoxide config
if ! command -v zoxide 2 1 &>/dev/null &>/dev/null; then
	curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
	if [[ $SHELL == '/bin/bash' ]]; then
		echo 'eval "$(zoxide init bash)"' >>~/.bashrc
	elif [[ $SHELL == '/bin/zsh' ]]; then
		echo 'eval "$(zoxide init zsh)"' >>~/.zshrc
	fi
fi

# command line tools config
## black
([[ -d ~/.config/black ]] && [[ -f ~/.config/black/.pyproject.toml ]]) || (mkdir -p ~/.config/black && ln -s ~/configure/format/pyproject.toml ~/.config/black/.pyproject.toml)
## clang-format
[[ -f ~/.clang-format ]] || ln -s ~/configure/format/clang-format ~/.clang-format
