#! /usr/bin/env bash
git submodule update --init --recursive --depth=1
cd ~/configure && git pull && git submodule update --remote --depth=1

# path config
[[ -d ~/.local/bin ]] || mkdir -p ~/.local/bin

# tmux config
ln -sf ~/configure/tmux.conf ~/.tmux.conf

# fish config
ln -sf ~/configure/config.fish ~/.config/fish/config.fish

# alacritty config
[[ -f ~/.config/alacritty/alacritty.toml ]] || (mkdir -p ~/.config/alacritty && ln -sf ~/configure/alacritty.toml ~/.config/alacritty/alacritty.toml)

# git config
ln -sf ~/configure/gitconfig ~/.gitconfig
ln -sf ~/configure/gitignore_global ~/.gitignore_global

# development tools config
## black
[[ -d ~/.config/black && -f ~/.config/black/.pyproject.toml ]] || (mkdir -p ~/.config/black && ln -s ~/configure/format/pyproject.toml ~/.config/black/.pyproject.toml)
## clang-format
[[ -f ~/.clang-format ]] || ln -s ~/configure/format/clang-format ~/.clang-format

# LazyVim config
rm -rf ~/.config/nvim
cp -r ~/configure/nvim ~/.config/nvim

# emacs config
mkdir -p ~/.emacs.d
rm -rf ~/.emacs.d/lisp/
cp ~/configure/emacs.d/init.el ~/.emacs.d/init.el
cp -r ~/configure/emacs.d/lisp ~/.emacs.d/lisp
