#! /usr/bin/env bash
git submodule update --init --recursive --depth=1
cd ~/configure && git pull && git submodule update --remote --depth=1

# path config
[[ -d ~/.local/bin ]] || mkdir -p ~/.local/bin

# tmux config
ln -sf ~/configure/software/tmux.conf ~/.tmux.conf

# fish config
[[ -f ~/.config/fish/config.fish ]] || (mkdir -p ~/.config/fish/ && ln -sf ~/configure/software/config.fish ~/.config/fish/config.fish)

# zsh config
ln -sf ~/configure/software/zshrc ~/.local/zshrc

# alacritty config
[[ -d ~/.config/alacritty ]] || mkdir -p ~/.config/alacritty
[[ -d ~/.config/alacritty/themes ]] || git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
ln -sf ~/configure/software/alacritty.toml ~/.config/alacritty/alacritty.toml

# wezterm config
ln -sf ~/configure/software/wezterm.lua ~/.wezterm.lua

# git config
ln -sf ~/configure/software/gitconfig ~/.gitconfig
ln -sf ~/configure/software/gitignore_global ~/.gitignore_global

# development tools config
## black
[[ -d ~/.config/black ]] || mkdir -p ~/.config/black
ln -sf ~/configure/format/pyproject.toml ~/.config/black/.pyproject.toml

## clang-format
ln -sf ~/configure/software/format/clang-format ~/.clang-format

# LazyVim config
[[ -d ~/.config/nvim ]] || git clone --depth=1 git@github.com:blackbhc/nvim.git ~/.config/nvim

# emacs config
[[ -d ~/.emacs.d ]] || git clone --depth=1 https://github.com/syl20bnr/spacemacs ~/.emacs.d
cat ~/configure/software/emacs.d/custom_spacemacs >>~/.spacemacs

# ipython and jupyter configure
[[ -d ~/.ipython/profile_default/startup ]] || mkdir -p ~/.ipython/profile_default/startup
ln -sf ~/configure/software/start.py ~/.ipython/profile_default/startup/start.py
