format = """
[░▒▓](#a3aed2)\
$os\
[](bg:#a3b9f2 fg:#a3aed2)\
[](bg:#a3b9f2 fg:#a3b9f2)\
$username\
[](bg:#769ff0 fg:#a3b9f2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$lua\
$conda\
[](fg:#212736 bg:#1d2230)\
$time\
$cmd_duration\
[ ](fg:#1d2230)\
\n$character"""

[username]
show_always = true
style_user = "bg:#a3b9f2 fg:#090c0c"
style_root = "bg:#a3b9f2 fg:#090c0c"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#a3aed2 fg:#090c0c"
disabled = false # Disabled by default
[os.symbols]
Macos = " "
Arch = " "
CentOS = "󱄚 "
Debian = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)[$read_only]($read_only_style)"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"
truncation_length = 10
truncation_symbol = "…/"
truncate_to_repo = false
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#212736"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[golang]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = " "
style = "bg:#212736"
format = '[ $symbol ($version) ]($style)'

[conda]
symbol = " "
style = "bg:#212736"
ignore_base = false
format = "[$symbol$environment]($style)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[cmd_duration]
min_time = 500
style = "bg:#1d2230"
format = " [$duration](fg:#a0a9cb bg:#1d2230)($style)"
