max_width                    = 100
hard_tabs                    = true
control_brace_style          = "AlwaysNextLine"
reorder_imports              = true
reorder_modules              = true
reorder_impl_items           = true
format_code_in_doc_comments  = true
format_macro_matchers        = true
edition                      = "2021"
struct_field_align_threshold = 50
enum_discrim_align_threshold = 50
